### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train.txt'

### ISSUE THREAD

**Issue by namnd00** [dangvansam98/phobert-text-classification#2]
When i run: python train_transformers_classifier_pytorch.py
I got an error like this:

_LOADDING TEXT FILE
Traceback (most recent call last):
  File "train_transformers_classifier_pytorch.py", line 334, in <module>
    main()
  File "train_transformers_classifier_pytorch.py", line 325, in main
    train_dataloader = dataloader_from_text(train_path, tokenizer=tokenizer, classes=classes, savetodisk=None, max_len=MAX_LEN, batch_size=64)
  File "train_transformers_classifier_pytorch.py", line 30, in dataloader_from_text
    with open(text_file, 'r') as f_r:
FileNotFoundError: [Errno 2] No such file or directory: 'train.txt'_

**Can you give me train.txt dataset file?**
Thank you.

**Comment by dangvansam** [comment]
file training có dung lượng khá lớn nên mình không upload lên đây, bạn có thể sử dụng file [test.txt](https://github.com/dangvansam98/phobert-text-classification/blob/main/test.txt) để chạy test
